### ISSUE TITLE
Uncaught TypeError: Observable_1.Observable.interval is not a function

### ISSUE THREAD

**Issue by sailei1** [KwintenP/rx-devtools#5]
![image](https://user-images.githubusercontent.com/1625409/45298643-b63dc700-b53b-11e8-9110-19f2f6442785.png)

**Comment by KwintenP** [comment]
Hi, 

What version of RxJS are you using. This project only works with version 5 and is not being maintained anymore. 

The reason can be found here: https://github.com/kwintenp/rx-devtools (disclaimer2)
